In [ ]:
import timeit
import numpy as np
import random

In [ ]:
timeit.timeit(lambda: set([1, 2, 3, 3, 2, 3]), number=100000)/100000

1.3558250007918105e-07

In [ ]:
timeit.timeit(lambda: np.unique(np.array([1, 2, 3, 3, 2, 3])), number=100000)/100000

2.41758749994915e-06

In [ ]:
timeit.timeit(lambda: list(set(np.array([1, 2, 3, 3, 2, 3]))), number=100000)/100000

9.425900000496767e-07

In [ ]:
timeit.timeit(lambda: len(set([False, False, False, True])), number=100000)/100000

1.1150167003506794e-07

In [ ]:
timeit.timeit(lambda: np.all([False, False, False, True]), number=100000)/100000

1.8215412501012907e-06

In [ ]:
timeit.timeit(lambda: len([x for x in [False, False, False, True] if x]), number=100000)/100000

8.014666993403807e-08

In [ ]:
timeit.timeit(lambda: np.random.choice(255, 250), number=100000)/100000

5.770555830094963e-06

In [ ]:
timeit.timeit(lambda: random.choices(range(255), k=250), number=100000)/100000

1.3298019590147305e-05

In [ ]:
data = [
    [False, True, True, False],
    [True, False, True, False],
    [True, True, False, False],
    [False, False, False, False],
    [True, True, True, False],
]

In [ ]:
np.array(data)

array([[False,  True,  True, False],
       [ True, False,  True, False],
       [ True,  True, False, False],
       [False, False, False, False],
       [ True,  True,  True, False]])

In [ ]:
np.sum(data, axis=0)

array([3, 3, 3, 0])

In [ ]:
timeit.timeit(lambda: np.where(np.any(data, axis=0))[0], number=100000)/100000

3.364718339871615e-06

In [ ]:
np.where(np.any(data, axis=0))[0]

array([0, 1, 2])

In [ ]:
np.where(np.sum(data, axis=0) > 0)[0]

array([0, 1, 2])

In [ ]:
timeit.timeit(lambda: np.where(np.sum(data, axis=0) > 0)[0], number=100000)/100000

3.910959170025308e-06

In [ ]:
[next((row for row in range(len(data)) if data[row][col]), None) for col in range(len(data[0]))]

[1, 0, 0, None]

In [ ]:
[i for i,paulis in enumerate(data) if len([p for p in paulis if p]) > 0]

[0, 1, 2, 4]

In [ ]:
np.where(np.any(data, axis=1))[0]

array([0, 1, 2, 4])